"""create health checks table

Revision ID: 2236311ce241
Revises: 2a305234ab23
Create Date: 2026-05-29 22:38:03.684747
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2236311ce241'
down_revision: Union[str, None] = '2a305234ab23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_checks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('service_id', sa.Uuid(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('healthy', 'degraded', 'down', name='health_check_status'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_health_checks_service_id_checked_at', 'health_checks', ['service_id', sa.literal_column('checked_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_health_checks_service_id_checked_at', table_name='health_checks')
    op.drop_table('health_checks')
    # On Postgres, the named enum type persists after the table is dropped;
    # remove it explicitly so the migration is cleanly reversible. (No-op on SQLite.)
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        sa.Enum(name="health_check_status").drop(bind, checkfirst=True)
    # ### end Alembic commands ###