"""create services table

Revision ID: 2a305234ab23
Revises: f0a1fd896f92
Create Date: 2026-05-29 21:14:02.126795
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2a305234ab23'
down_revision: Union[str, None] = 'f0a1fd896f92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('environment', sa.Enum('dev', 'uat', 'prod', name='environment'), nullable=False),
    sa.Column('status', sa.Enum('healthy', 'degraded', 'down', 'unknown', name='service_status'), nullable=False),
    sa.Column('repo_url', sa.String(length=2048), nullable=True),
    sa.Column('health_url', sa.String(length=2048), nullable=True),
    sa.Column('last_deployed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_user_id'), 'services', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_services_user_id'), table_name='services')
    op.drop_table('services')
    # On Postgres, named enum types persist after the table is dropped; remove
    # them explicitly so the migration is cleanly reversible. (No-op on SQLite.)
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        sa.Enum(name="service_status").drop(bind, checkfirst=True)
        sa.Enum(name="environment").drop(bind, checkfirst=True)
    # ### end Alembic commands ###